### ISSUE TITLE
What to put in the array?

### ISSUE THREAD

**Issue by SarcasticNoodle** [timmcleod/turtlecoin-walletd-rpc-php#1]
I just want to send trtl with this lib, but it gives me this error:
{"error":{"code":-32700,"data":{"application_code":7},"message":"Bad address"},"id":2,"jsonrpc":"2.0"}

This is my $transfers array
$transfers = array("address" => "TRTLuxns7wcNqnoBMjYrMEhRTQdq8AKcwi1G58uqfgdiMqhDZS1fyaAenTwKiPgryn5TQNukGkQScdVqExcLj9XE5EZWvw8Y9R5", "amount" => 10);

Whats wrong and yes, this is a real trtl address

**Comment by timmcleod** [comment]
Hey @TheDOme6, if you don't mind, post your question on the TurtleCoin fork (https://github.com/turtlecoin/turtlecoin-walletd-rpc-php). New dev will happen there.

**Comment by timmcleod** [comment]
Looks like the issues tab isn't enabled on that fork. I'll ask Rock to enable it. 

Post your code and I'll take a look. How are you configuring the instance? Are you able to call any of the other methods?

**Comment by timmcleod** [comment]
@TheDOme6 I believe the problem is that your transfers array needs to be wrapped in another array. It's possible to send a transaction to 1 or several addresses at once. Take a look at the ByteCoin RPC docs and you'll see what I mean: https://wiki.bytecoin.org/wiki/Send_transaction_-_Bytecoin_RPC_Wallet_API

Try passing this instead:
```
$transfers = [
   [
      "address" => "TRTLuxns7wcNqnoBMjYrMEhRTQdq8AKcwi1G58uqfgdiMqhDZS1fyaAenTwKiPgryn5TQNukGkQScdVqExcLj9XE5EZWvw8Y9R5", 
      "amount"  => 10
   ]
];
```

**Comment by SarcasticNoodle** [comment]
Worked thanks!
